apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
  labels: # <-- moved under metadata
    app: rest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: rest
          image: us-central1-docker.pkg.dev/demucs-lab/msas/msas-rest:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: WORK_QUEUE
              value: "toWorker"
            - name: LOG_LIST
              value: "logging"
            - name: MINIO_HOST
              value: "minio-proj.minio-ns.svc.cluster.local:9000"
            - name: MINIO_SECURE
              value: "false"
            - name: BUCKET_IN
              value: "queue"
            - name: BUCKET_OUT
              value: "output"
            - name: MODEL_NAME
              value: "htdemucs"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: MINIO_SECRET_KEY
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  selector:
    app: rest
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: NodePort
